/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('actors').del()
  await knex('actors').insert([
    { id: 1, name: 'Robert Downey Jr.', age: 58, gender: 'Male' },
    { id: 2, name: 'Scarlett Johansson', age: 39, gender: 'Female' },
    { id: 3, name: 'Chris Evans', age: 43, gender: 'Male' },
    { id: 4, name: 'Tom Holland', age: 28, gender: 'Male' },
    { id: 5, name: 'Gal Gadot', age: 39, gender: 'Female' },
    { id: 6, name: 'Dwayne Johnson', age: 52, gender: 'Male' },
    { id: 7, name: 'Zendaya', age: 27, gender: 'Female' },
    { id: 8, name: 'Ryan Reynolds', age: 47, gender: 'Male' },
    { id: 9, name: 'Leonardo DiCaprio', age: 49, gender: 'Male' },
    { id: 10, name: 'Natalie Portman', age: 43, gender: 'Female' },
    { id: 11, name: 'Brad Pitt', age: 60, gender: 'Male' },
    { id: 12, name: 'Angelina Jolie', age: 49, gender: 'Female' },
    { id: 13, name: 'Tom Cruise', age: 62, gender: 'Male' },
    { id: 14, name: 'Emma Watson', age: 33, gender: 'Female' },
    { id: 15, name: 'Keanu Reeves', age: 59, gender: 'Male' },
    { id: 16, name: 'Jennifer Lawrence', age: 34, gender: 'Female' },
    { id: 17, name: 'Johnny Depp', age: 61, gender: 'Male' },
    { id: 18, name: 'Chris Hemsworth', age: 41, gender: 'Male' },
    { id: 19, name: 'Margot Robbie', age: 34, gender: 'Female' },
    { id: 20, name: 'Matt Damon', age: 53, gender: 'Male' },
    { id: 21, name: 'Meryl Streep', age: 74, gender: 'Female' },
    { id: 22, name: 'Will Smith', age: 55, gender: 'Male' },
    { id: 23, name: 'Julia Roberts', age: 56, gender: 'Female' },
    { id: 24, name: 'Hugh Jackman', age: 56, gender: 'Male' },
    { id: 25, name: 'Anne Hathaway', age: 41, gender: 'Female' },
    { id: 26, name: 'George Clooney', age: 63, gender: 'Male' },
    { id: 27, name: 'Charlize Theron', age: 49, gender: 'Female' },
    { id: 28, name: 'Christian Bale', age: 50, gender: 'Male' },
    { id: 29, name: 'Amy Adams', age: 50, gender: 'Female' },
    { id: 30, name: 'Daniel Craig', age: 56, gender: 'Male' },
    { id: 31, name: 'Rami Malek', age: 42, gender: 'Male' },
    { id: 32, name: 'Emily Blunt', age: 41, gender: 'Female' },
    { id: 33, name: 'Joaquin Phoenix', age: 49, gender: 'Male' },
    { id: 34, name: 'Emma Stone', age: 35, gender: 'Female' },
    { id: 35, name: 'Jake Gyllenhaal', age: 43, gender: 'Male' },
    { id: 36, name: 'Chris Pratt', age: 45, gender: 'Male' },
    { id: 37, name: 'Sandra Bullock', age: 60, gender: 'Female' },
    { id: 38, name: 'Ben Affleck', age: 51, gender: 'Male' },
    { id: 39, name: 'Kate Winslet', age: 48, gender: 'Female' },
    { id: 40, name: 'Mark Ruffalo', age: 56, gender: 'Male' },
    { id: 41, name: 'Reese Witherspoon', age: 48, gender: 'Female' },
    { id: 42, name: 'Harrison Ford', age: 82, gender: 'Male' },
    { id: 43, name: 'Cate Blanchett', age: 54, gender: 'Female' },
    { id: 44, name: 'Samuel L. Jackson', age: 75, gender: 'Male' },
    { id: 45, name: 'Morgan Freeman', age: 87, gender: 'Male' },
    { id: 46, name: 'Helen Mirren', age: 78, gender: 'Female' },
    { id: 47, name: 'Robert De Niro', age: 81, gender: 'Male' },
    { id: 48, name: 'Al Pacino', age: 84, gender: 'Male' },
    { id: 49, name: 'Javier Bardem', age: 55, gender: 'Male' },
    { id: 50, name: 'Penélope Cruz', age: 50, gender: 'Female' },
    { id: 51, name: 'Eddie Murphy', age: 63, gender: 'Male' },
    { id: 52, name: 'Viola Davis', age: 59, gender: 'Female' },
    { id: 53, name: 'Michael B. Jordan', age: 37, gender: 'Male' },
    { id: 54, name: 'Tilda Swinton', age: 63, gender: 'Female' },
    { id: 55, name: 'Idris Elba', age: 51, gender: 'Male' },
    { id: 56, name: 'Lupita Nyong’o', age: 41, gender: 'Female' },
    { id: 57, name: 'Daniel Day-Lewis', age: 67, gender: 'Male' },
    { id: 58, name: 'Jessica Chastain', age: 47, gender: 'Female' },
    { id: 59, name: 'Timothée Chalamet', age: 28, gender: 'Male' },
    { id: 60, name: 'Florence Pugh', age: 28, gender: 'Female' },
    { id: 61, name: 'Mahershala Ali', age: 50, gender: 'Male' },
    { id: 62, name: 'Octavia Spencer', age: 54, gender: 'Female' },
    { id: 63, name: 'Gal Gadot', age: 39, gender: 'Female' },
    { id: 64, name: 'Vin Diesel', age: 57, gender: 'Male' },
    { id: 65, name: 'John Boyega', age: 32, gender: 'Male' },
    { id: 66, name: 'Letitia Wright', age: 30, gender: 'Female' },
    { id: 67, name: 'Charlize Theron', age: 49, gender: 'Female' },
    { id: 68, name: 'Adam Driver', age: 40, gender: 'Male' },
    { id: 69, name: 'Anya Taylor-Joy', age: 28, gender: 'Female' },
    { id: 70, name: 'Sebastian Stan', age: 41, gender: 'Male' },
    { id: 71, name: 'Donald Glover', age: 40, gender: 'Male' },
    { id: 72, name: 'Saoirse Ronan', age: 30, gender: 'Female' },
    { id: 73, name: 'Tom Hardy', age: 46, gender: 'Male' },
    { id: 74, name: 'Zoe Saldana', age: 46, gender: 'Female' },
    { id: 75, name: 'Jude Law', age: 51, gender: 'Male' },
    { id: 76, name: 'Eva Green', age: 43, gender: 'Female' },
    { id: 77, name: 'Oscar Isaac', age: 45, gender: 'Male' },
    { id: 78, name: 'Ryan Gosling', age: 43, gender: 'Male' },
    { id: 79, name: 'Chadwick Boseman', age: 44, gender: 'Male' },
    { id: 80, name: 'Elisabeth Moss', age: 41, gender: 'Female' },
    { id: 81, name: 'Halle Berry', age: 57, gender: 'Female' },
    { id: 82, name: 'Jodie Comer', age: 31, gender: 'Female' },
    { id: 83, name: 'Andrew Garfield', age: 41, gender: 'Male' },
    { id: 84, name: 'Kristen Stewart', age: 34, gender: 'Female' },
    { id: 85, name: 'Henry Cavill', age: 41, gender: 'Male' },
    { id: 86, name: 'Millie Bobby Brown', age: 20, gender: 'Female' },
    { id: 87, name: 'Tom Hanks', age: 67, gender: 'Male' },
    { id: 88, name: 'Woody Harrelson', age: 62, gender: 'Male' },
    { id: 89, name: 'Paul Rudd', age: 55, gender: 'Male' },
    { id: 90, name: 'Melissa McCarthy', age: 53, gender: 'Female' },
    { id: 91, name: 'Amy Poehler', age: 52, gender: 'Female' },
    { id: 92, name: 'Steve Carell', age: 62, gender: 'Male' },
    { id: 93, name: 'Jason Momoa', age: 45, gender: 'Male' },
    { id: 94, name: 'Zendaya', age: 27, gender: 'Female' },
    { id: 95, name: 'John Krasinski', age: 44, gender: 'Male' },
    { id: 96, name: 'Gal Gadot', age: 39, gender: 'Female' },
    { id: 97, name: 'Chris Pine', age: 44, gender: 'Male' },
    { id: 98, name: 'Michael Fassbender', age: 47, gender: 'Male' },
    { id: 99, name: 'Tessa Thompson', age: 41, gender: 'Female' },
    { id: 100, name: 'Will Ferrell', age: 57, gender: 'Male' }
  ]);
}
